version: "3"
services:
  dash:
    build: ./Dash
    ports:
      - 8050:8050
  api:
    build: ./API
    ports:
      - 8000:8000
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./BD/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: credito_bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
